Update ci.yml

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -51,34 +51,34 @@ jobs:
 #       - uses: nosborn/github-action-markdown-cli@5cfe13755d7cdc2d0d01b69c7900cfd3fa37f4a4 # v3.2.0
 #         with:
 #           files: .
-#   verify-generated:
-#     runs-on: ubuntu-latest
-#     steps:
-#       - name: Harden Runner
-#         uses: step-security/harden-runner@18bf8ad2ca49c14cbb28b91346d626ccfb00c518 # v2.1.0
-#         with:
-#           egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs
-#       - uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3.3.0
-#       - uses: actions/setup-go@6edd4406fa81c3da01a34fa6f6343087c207a568 # v3.5.0
-#         with:
-#           go-version-file: go.mod
-#           cache: true
-#       - name: Generate all
-#         run: |
-#           make generate-all
-#       - name: Verify changed files
-#         uses: tj-actions/verify-changed-files@a148bdba9d2477a2aca3537bd6bc7a7af54b06f2 # v13
-#         id: verify-changed-files
-#         with:
-#           files: |
-#             **/*
-#       - name: Fail job is any changed files
-#         if: steps.verify-changed-files.outputs.files_changed == 'true'
-#         run: |
-#           errorMsg="::error::\
-#             Changed files: ${{ steps.verify-changed-files.outputs.changed_files }}\
-#             \nPlease run 'make generate-all' locally and commit the changes"
-#           echo -e "$errorMsg" && exit 1
+  verify-generated:
+    runs-on: ubuntu-latest
+    steps:
+      - name: Harden Runner
+        uses: step-security/harden-runner@18bf8ad2ca49c14cbb28b91346d626ccfb00c518 # v2.1.0
+        with:
+          egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs
+      - uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3.3.0
+      - uses: actions/setup-go@6edd4406fa81c3da01a34fa6f6343087c207a568 # v3.5.0
+        with:
+          go-version-file: go.mod
+          cache: true
+      - name: Generate all
+        run: |
+          make generate-all
+      - name: Verify changed files
+        uses: tj-actions/verify-changed-files@a148bdba9d2477a2aca3537bd6bc7a7af54b06f2 # v13
+        id: verify-changed-files
+        with:
+          files: |
+            **/*
+      - name: Fail job is any changed files
+        if: steps.verify-changed-files.outputs.files_changed == 'true'
+        run: |
+          errorMsg="::error::\
+            Changed files: ${{ steps.verify-changed-files.outputs.changed_files }}\
+            \nPlease run 'make generate-all' locally and commit the changes"
+          echo -e "$errorMsg" && exit 1
 #   test:
 #     needs: verify-generated
 #     runs-on: ubuntu-latest
